### ISSUE TITLE
keep_docs_dir is not used for nav_repos and !import statements

### ISSUE THREAD

**Issue by wday-cs** [jdoiro3/mkdocs-multirepo-plugin#103]
I've been trying to configure the `nav_repos` and `keep_docs_dir` settings to `false`, but I'm facing an issue where it doesn't move all the docs up from the `docs_dir` folder.

I tried debugging the problem to identify any mistakes on my end, but it's possible that there's a bug in the plugin.

During my investigation, I noticed a few things that might help in figuring out the issue:
- In [`plugins.py`](https://github.com/jdoiro3/mkdocs-multirepo-plugin/blob/main/mkdocs_multirepo_plugin/plugin.py#L268-L270):
  - It assigns the `nav_repo` within the loop to `self.repo`. Shouldn't it be `self.nav_repo` instead?
  - Additionally, the values are assigned within the loop instead of after calling `space_clone`.
  - It seems that `batch_import` is not called for `nav_repos`, but this might be due to the case where `self.repo` is used.
- In [structure.py](https://github.com/jdoiro3/mkdocs-multirepo-plugin/blob/main/mkdocs_multirepo_plugin/structure.py#L383-L390):
  - I couldn't trigger the `import_docs` else condition, where the `mv_docs_up.sh` script is executed.
  - `import_docs` is not called in `handle_nav_repos_import`.

I observed similar behavior with the `!import` statement, where setting `keep_docs_up=False` didn't move the docs up as expected.

I attempted to add both `nav_repo` and `!import` statement for the same repository, but it didn't properly set up the navigation. I also tried each of them individually.

Here is the `mkdocs.yml` configuration for your reference:

```yaml
- multirepo:
    cleanup: false
    # keep_docs_dir: false
    nav_repos:
      - name: Runtime
        import_url: https://github.com/example/example?branch=ml-69231&docs_dir=docs/*&keep_docs_dir=False
        imports: [
          /docs/*,
          /mkdocs.yml,
          # includes/*
        ]

nav:
  - Directory: index.md
  - Runtime: '!import https://github.com/example/example?docs_dir=docs/*&config=mkdocs.yml&keep_docs_dir=False&branch=ml-69231'
```
