### ISSUE TITLE
multirepo-plugin is not compatible with mkdocstrings

### ISSUE THREAD

**Issue by stoney95** [jdoiro3/mkdocs-multirepo-plugin#110]
@jdoiro3 I am having trouble with the interaction of multirepo-plugin and mkdocstrings. 

Repo A: This provides a package. Let's call this package common. Thus, we have the following folder structure
```
common /
  __init__.py
  other_stuff.py
docs /
  index.md
mkdocs.yaml
```

Here we use mkdocstrings[python] to automatically build doc strings. A simplified version of index.md looks like this

```
:::common
```

----

Repo B: This imports Repo A. It uses the following configuration:

```yaml
nav:
  - Home: index.md
  - Code Reference:
    - Common: '!import some-gitlab.com/user/common.git?branch=main&extra_imports=["common"]'
    
plugins:
  - mkdocstrings:
      handlers: 
        python:
          paths: [common] # This is not working
  - multirepo:
      cleanup: false
      temp_dir: .deps
```

Running this will create the .deps folder and download all the files that I am looking for: 

```
.deps /
  code-reference /
    common /
      common /
         __init__.py
         other_stuff.py
      index.md
      mkdocs.yaml
```

Nonetheless I get the following error when trying to run `mkdocs serve`:

```
ERROR   -  mkdocstrings: No module named 'common'
ERROR   -  Error reading page 'code-reference/common/index.md':
ERROR   -  Could not collect 'common'
```

---

Serving mkdocs in Repo A (no multirepo involved) works. I use the following mkdocs settings:

```yaml
plugins:
  - mkdocstrings:
       handlers: 
         python:
           paths: [common]
```

When importing Repo A into Repo B `paths: [common]` is not working. I can resolve the issue if I manually copy the common folder to the root of Repo B. I also tried to set the absolute path like this `paths: [.deps/code-reference/common/common]`. This does not work. I also tried this: `paths: [code-reference/common/common]`. Did not work either. 

I checked out a couple of issues in this project. They helped me to use the `extra_imports` parameter. But could not resolve the module not found issue. Issues I referenced:

- https://github.com/jdoiro3/mkdocs-multirepo-plugin/issues/42
- https://github.com/jdoiro3/mkdocs-multirepo-plugin/issues/35
- https://github.com/jdoiro3/mkdocs-multirepo-plugin/issues/3

Also tagging @pawamoy, as he helped out in #3
