### ISSUE TITLE
Nav bar does not load page metadata

### ISSUE THREAD

**Issue by oleg-nenashev** [jdoiro3/mkdocs-multirepo-plugin#128]
In https://github.com/wiremock/wiremock.org/pull/228 I am trying to migrate the WireMock documentation from Jekyll to a combination of MkDocs + Multi-Repo Plugin + Material for MkDocs. Jekyll uses page `title` metadata, and it is normally supported in MkDocs too. However, Multi-repo plugin seems to not consult with this metadata

Config:

```yaml
  - Getting started:
      - Overview: overview
      - quickstart/java-junit
      - download-and-installation
      - getting-started
      - FAQ: faq
```

Page meadata sample:

```
---
layout: docs
title: WireMock Tutorials
meta_title: Listing of WireMock Quick Starts and Tutorials
toc_rank: 10
```

## Actual behavior

![image](https://github.com/jdoiro3/mkdocs-multirepo-plugin/assets/3000480/d3db182d-b402-444c-ad8d-40a8a17fa4ca)

## Expected behavior

Title metadata is loaded
