### ISSUE TITLE
Having to log into github on build

### ISSUE THREAD

**Issue by tobytwigger** [jdoiro3/mkdocs-multirepo-plugin#13]
Hey! Thanks for this plugin, it's exactly what I've been looking for for a new docs site.

I'm using this plugin to pull docs from several github repositories. Whenever I run `mkdocs build` or `mkdocs serve` github asks for a username and password and I have to use `git` and a personal access token to log in. I can change the URLs to `git+ssh://git@github.com/...` to make it use my ssh config, but not in CI.

To authenticate you suggest setting an AccessToken environmental variable, but the header is a `bearer` token. Github often uses a heaer of `Authorization: token personal-access-token` instead, and a personal access token is easy to get a hold of.

Do you know if I'm doing something wrong, or would you be interested if I added a GithubAccessToken environment variable to set a token header?

Our code:

```
// main mkdocs.yml
site_name: Example
site_url: https://example.com
nav:
  - Home: 'index.md'
  - SDK: '!import https://github.com/my-organisation/sdk?branch=develop'
theme:
  name: material
plugins:
  - multirepo
  - search
```

```
// sdk mkdocs.yml
site_name: 'sdk'
edit_uri: /blob/develop/
nav:
  - Home: index.md
  - Authorization: authorization.md
  - Navigation: navigation.md


plugins:
  multirepo:
    imported_repo: true
    url: https://github.com/my-organisation/sdk
    section_name: sdk
    dirs: ["mkdocs.yml", "docs"]
    branch: develop

```
