### ISSUE TITLE
Question: local `file://` path in `!import` statement on Windows

### ISSUE THREAD

**Issue by 9Lukas5** [jdoiro3/mkdocs-multirepo-plugin#134]
Hey, I tested that yesterday at home on a linux machine, using in the mkdocs yaml this:

```yaml
site_name: Project-A

plugins:
  - multirepo:
      cleanup: false


nav:
  - index.md
  - Project-B: '!import file://///some/absolute/path/to/project-B?branch=main'
```

I tried this today on a windows machine using the git for windows bash, using various combinations like:

- `file://///c/some/absolute/path/to/project-B?branch=main`
- `file:///c/some/absolute/path/to/project-B?branch=main`
- `file:C:\\some/absolute/path/to/project-B?branch=main`
- `file://///C:\\some\\absolute\\path\\to\\project-B?branch=main`

But it always complains it can't clone/the target path wouldn't seem to be a valid Git-Repo.
Anyone an idea, how to put the path for local development correct on Windows using the Git-Bash?

That was my idea of a workaround until #129 is dealt with (and on my linux setup it works)^^
