### ISSUE TITLE
Import the content of multiple files (incl. ones from external repos) into one file

### ISSUE THREAD

**Issue by nihalshah-dev** [jdoiro3/mkdocs-multirepo-plugin#140]
Hi everyone,

**Summary:**
From what i understand from multi-repo plugin we can import docs using `!import` statement as well.
Like this - 
```
nav:
  - Home: 'index.md'
  - MicroService: '!import {url}?branch={branch}&docs_dir={path}&multi_docs={True|False}&config={filename}.yml&keep_docs_dir={True|False}'
```
Here we are trying to import only one url. The `!import` statement is designed to import documentation from a single URL.

**Proposal Details:**
Can the plugin handle the inclusion of content from multiple URLs within a single `!import ` statement.

**Like this  -** 
 ```
nav:
  - Home: 'index.md'
  - MicroService: '!import {url1, url2, url3}?branch={branch}&docs_dir={path}&multi_docs={True|False}&config={filename}.yml&keep_docs_dir={True|False}'
```
**Instead of -**
```
nav:
  - Home: 'index.md'
  - MicroService:
    - '!import {url1}?branch={branch}&docs_dir={path1}&multi_docs=True&config={filename1}.yml&keep_docs_dir=True'
    - '!import {url2}?branch={branch}&docs_dir={path2}&multi_docs=True&config={filename2}.yml&keep_docs_dir=True'
    - '!import {url3}?branch={branch}&docs_dir={path2}&multi_docs=True&config={filename2}.yml&keep_docs_dir=True'

```

It will be really cool if i could use only one import statement instead of multiple and just extract the content from multiple repos (including ones from external repos)

Is this possible? Really appreciate for any help here. Thanks!
