### ISSUE TITLE
Group imports under same path

### ISSUE THREAD

**Issue by ashleynilo** [jdoiro3/mkdocs-multirepo-plugin#160]
Hello, 

I am able to import files from multiple repos over, however I want all of these files to be imported into a specific folder, or at least group them together under a certain path.

For example - taking the README example something like this

```
plugins:
  - search
  - multirepo:
      # (optional) tells multirepo to cleanup the temporary directory after site is built.
      cleanup: false
      nav_repos:
        - name: backstage
          import_url: https://github.com/backstage/backstage
          # forward slash is needed in '/README.md' so that only the README.md in the root
          # directory is imported and not all README.md files.
          imports: [
            docs/publishing.md, docs/integrations/index.md, /README.md,
            # asset files needed
            docs/assets/*
            ]
        - name: fast-api
          import_url: https://github.com/tiangolo/fastapi
          imports: [docs/en/docs/index.md]

nav:
  - Tutorials:
      - Backstage:
          - Home: tutorials/backstage/README.md
          - Integration: tutorials/backstage/docs/integrations/index.md
          - Publishing: tutorials/backstage/docs/publishing.md
      - FastAPI: tutorials/fast-api/docs/en/docs/index.md
```

I would have both directories under a path called tutorials and in turn the URL will have tutorials in it. 

Is this possible?
