### ISSUE TITLE
nav_repos not supporting `main` branch

### ISSUE THREAD

**Issue by sammbetts** [jdoiro3/mkdocs-multirepo-plugin#163]
I am getting the following error `fatal: Remote branch master not found in upstream origin` when using `nav_repos` - my head branch is `main` not `master` as will be the case with all newer repos - is there any way to set this? If I add `tree/main` to the end of the `import_url` it tells me that the repo can't be found.

Many thanks!

**Comment by jdoiro3** [comment]
Have you tried setting `branch` for the `import_url`?

```yaml
nav_repos:
        - name: pydantic
          import_url: https://github.com/samuelcolvin/pydantic?branch=main
```
