### ISSUE TITLE
Doesn't work for self hosted github enterprise?

### ISSUE THREAD

**Issue by acastro2** [jdoiro3/mkdocs-multirepo-plugin#2]
I think it doesn't work for self-hosted github enterprise. The URL here is git.<company>.com (only vpn accessible), and when running mkdocs serve:

```bash
INFO     -  Multirepo plugin is importing docs for section Section 1
[Errno 2] No such file or directory: 'where'
```

This is an example of the mkdocs.yml:

```yaml
# Project information
site_name: Platform Wiki
site_description: Centralized location for all documentation
site_author: Platform

# Repository
repo_name: platform/centralized-docs
repo_url: https://git.<company>.com/platform/centralized-docs

nav:
  - Home: index.md
  - Login Server: '!import https://git.<company>.com/<org>/<repo>@master'

# Configuration
theme:
  name: material
  palette:
    primary: indigo
    accent: pink
    scheme: default

plugins:
  - multirepo:
      # (optional) tells multirepo to cleanup the temporary directory after site is built.
      cleanup: true
      # (optional) tells multirepo what the temp directory should be called
      temp_dir: multirepo_docs

```
