### ISSUE TITLE
github actions fails

### ISSUE THREAD

**Issue by andreas-paul** [jdoiro3/mkdocs-multirepo-plugin#33]
Hi there,

thanks for providing this plugin for MkDocs! I've been trying to configure it but unfortunately I can't get it to work properly. Specifically, I am receiving the following error, when trying to clone a private repository in a Github action workflow:

```
mkdocs_multirepo_plugin.util.GitException: 
Cloning into 'project'...
fatal: could not read Username for 'https://github.com/': No such device or address
```
What I have tried so far is to add a personal access token from my account in github actions like so:

```
name: deploy to github pages
on:
  push:
    branches:
      - master 
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.x
      - run: pip install mkdocs-material mkdocs-autolinks-plugin mkdocs-multirepo-plugin python-slugify
      - run: mkdocs gh-deploy --force
        env:
            AccessToken: ${{ secrets.docs_build_access }}
```

I have also tried to set environment variables directly for the private repo, to no avail. I'm at a loss here about how to configure github to enable access from one repo to the other, all of them private.  Any ideas or help would be appreciated!
