### ISSUE TITLE
Misunderstanding branch

### ISSUE THREAD

**Issue by gmcfrear** [jdoiro3/mkdocs-multirepo-plugin#38]
Hi,
I seem to be misunderstanding your docs.

in my mkdocs.yaml. I have

```
plugins:
  - multirepo:
      cleanup: false
      branch: main
      repos:
        - section: Repo1
          import_url: 'https://github.myenterprise.com/center/gfp-test-01'
          branch: main
          edit_uri: /blob/main/
        - section: Repo2
          import_url: 'https://github.myenterprise.com/center/gfp-test-02'
          branch: main
          edit_uri: /blob/main/
        - section: Repo3
      ```
and the result I got was:

mkdocs_multirepo_plugin.util.GitException:
Cloning into 'repo3'...
warning: Could not find remote branch master to clone.
fatal: Remote branch master not found in upstream origin

then I edited the plugin
https://github.com/jdoiro3/mkdocs-multirepo-plugin/blob/main/mkdocs_multirepo_plugin/plugin.py#L21

and it worked
INFO     -  [16:13:12] Browser connected: http://localhost:8000/
INFO     -  [16:13:16] Browser connected: http://localhost:8000/repo1/about/
INFO     -  [16:13:21] Browser connected: http://localhost:8000/repo2/about/
INFO     -  [16:13:23] Browser connected: http://localhost:8000/repo3/about/
INFO     -  [16:13:28] Browser connected: http://localhost:8000/repo3/about/

Where am I going wrong?
