### ISSUE TITLE
AttributeError: 'str' object has no attribute 'items' (Not related to `navigation.indexes`)

### ISSUE THREAD

**Issue by the-real-cphillips** [jdoiro3/mkdocs-multirepo-plugin#39]
I know this error has come up before and it was determined to be related to `navigation.indexes` but this is different.

Here's my `mkdocs.yml` where I'm using `multirepo`

```yaml
nav
  - Home: index.md
  - Tool: '!import https://github.com/{user}/{repo}'
```

Here is the `nav` from `mkdocs.yaml` inside the Tool repo:

```yaml
nav:
  - Welcome: index.md
  - ...
  - Advanced Features:
    - feature 1: feat1.md
```

When using `!import` the error is experienced.
If I use the `repos` section under `plugins`, there is no problem importing.
