### ISSUE TITLE
Issues when running multirepo

### ISSUE THREAD

**Issue by SteveRosam** [jdoiro3/mkdocs-multirepo-plugin#66]
When i run `mkdocs serve` I get the following output.
```
INFO     -  Building documentation...
WARNING  -  Multirepo plugin is ignoring plugins.multirepo.repos. Nav takes precedence
INFO     -  Multirepo plugin importing docs...
INFO     -  Cleaning site directory
INFO     -  Multirepo plugin is cleaning up temp_dir/
INFO     -  Documentation built in 0.23 seconds
INFO     -  [16:55:53] Watching paths for changes: 'docs', 'mkdocs.yml'
INFO     -  [16:55:53] Serving on http://127.0.0.1:8000/
WARNING  -  [16:55:54] "GET /quix-apis/ HTTP/1.1" code 404
INFO     -  [16:56:07] Browser connected: http://localhost:8000/
```
This is my yaml file.. I mostly copied the bits from your readme.

```
site_name: My Docs
 
nav:
  - Home: 'index.md'
  
plugins:
  - search
  - multirepo:
      # (optional) tells multirepo to cleanup the temporary directory after site is built.
      cleanup: true
      repos:
        - section: Backstage
          # you can define the edit uri path
          import_url: 'https://github.com/backstage/backstage?edit_uri=/blob/master/'
        - section: Monorepo
          import_url: 'https://github.com/backstage/mkdocs-monorepo-plugin?edit_uri=/blob/master/'
        - section: 'Techdocs-cli'
          # note that the branch is still specified in the url
          import_url: 'https://github.com/backstage/techdocs-cli?branch=main&edit_uri=/blob/main/'
        - section: FastAPI
          import_url: 'https://github.com/tiangolo/fastapi?docs_dir=docs/en/docs/*'
        - section: Monorepo Multi Docs
          import_url: https://github.com/backstage/mkdocs-monorepo-plugin?multi_docs=True&docs_dir=sample-docs/*
        - section: 'Django REST'
          section_path: python # Put this under the python menu entry
          import_url: 'https://github.com/encode/django-rest-framework'
        - section: 'Cookiecutter Pypackage'
          section_path: python # Put this under the python menu entry
          import_url: 'https://github.com/zillionare/cookiecutter-pypackage'
        - section: 'Pydantic'
          section_path: python # Put this under the python menu entry
          import_url: 'https://github.com/samuelcolvin/pydantic?branch=main'
```

I wasn't sure from the docs whether I needed the nav section as well as the plugins config. But without the nav section it fails to build.
I noticed WITH the nav section that the output is saying Nav take precedence.

**Comment by SteveRosam** [comment]
Example of my issue.
![image](https://user-images.githubusercontent.com/100689438/197578283-67c0c5d7-395b-4a69-b1fc-c2afeaf0da0f.png)

**Comment by tcarmet** [comment]
Was having the same issue as you, then I saw the warning message:

```shell
WARNING  -  Multirepo plugin is ignoring plugins.multirepo.repos. Nav takes precedence
```

Either remove the `nav` section in the `mkdocs.yml` or use the following syntax:

```yaml
# mkdocs.yml
nav:
  - Home: index.md
  - Backstage: '!import https://github.com/backstage/backstage?edit_uri=/blob/master/'
```

**Comment by SteveRosam** [comment]
Hi @tcarmet, 

removing the nav section crashes mkdocs

This is my yaml file

```
site_name: 'Docs'

#nav:
#  - Home: index.md

plugins:
  - search
  - multirepo:
      # (optional) tells multirepo to cleanup the temporary directory after site is built.
      cleanup: false
      repos:
        - section: Backstage
          # you can define the edit uri path
          import_url: 'https://github.com/backstage/backstage?edit_uri=/blob/master/'
        - section: Monorepo
          import_url: 'https://github.com/backstage/mkdocs-monorepo-plugin?edit_uri=/blob/master/'
```

**Comment by SteveRosam** [comment]
This also crashes mkdocs..

```
site_name: 'Docs'

nav:
  - Home: index.md
  - Backstage: '!import https://github.com/backstage/backstage'
  
plugins:
  - search
  - multirepo:
      # (optional) tells multirepo to cleanup the temporary directory after site is built.
      cleanup: false

```
