### ISSUE TITLE
`keep_docs_dir` not updating the nav-section of imported repo? 

### ISSUE THREAD

**Issue by DavidBuettner** [jdoiro3/mkdocs-multirepo-plugin#81]
Hi @jdoiro3 

I tried to use the new feature `keep_docs_dir`, but ran into an issue which I am not sure how to solve. 

I have a repository 
* A, which builds documentation using mkdocs in very basic way. 
* B, which imports A using the `keep_docs_dir` parameter

Nevertheless, it seems that I need to change the references in `A/mkdocs,yml` in order to make B build correctly.  
If I do this, though, A does not work correctly anymore on itself. 

Am I missing something or would the plugin need to fix the imported nav section by prepending the `docs_dir` to all file references? 

Most likely I am just missing something obvious - thanks for some feedback in advance! 
Also thanks for working on these updates, 

Cheers,
David

PS: If there is something missing in the code and you can point me in the right direction where to look, I might find some time to create a PR as well...

**Comment by jdoiro3** [comment]
I think I know what your talking about but just to make sure can you provide me an example `mkdocsyml` for both repo A and B?

**Comment by DavidBuettner** [comment]
Hi @jdoiro3 

sorry for the long delay.   

Simplified `mkdocs.yml` (relevant parts) are this: 

## Working setup so that A builds on its own

```yml
nav:
  - Home: "index.md"
  - About: "about.md"
```

with `index.md` and `about.md` inside `./docs` which is also the default `docs_dir`. 

## Using `keep_docs_dir` in repo B

```yml
plugins:
  - multirepo:
      cleanup: false # cache imported repos when serving locally
      temp_dir: .deps
      keep_docs_dir: true
```
This fails with the `mkdocs.yml` described above, but works, if I add the `docs` to the `mkdocs.yml` from A like this: 

```yml
nav:
  - Home: "./docs/index.md"
  - About: "./docs/about.md"
```


## Assumption

I assume that in some place, when NOT using `keep_docs_dir`, the `docs_dir` of the target (here A) is removed from some internal path, but has not been updated to check if `keep_docs_dir` is set? 


I hope this helps, feel free to ping me for more information if this was not clear enough!

Thanks a lot!
