### ISSUE TITLE
Allow extra metadata on the repos section for rendering purposes

### ISSUE THREAD

**Issue by coloboxp** [jdoiro3/mkdocs-multirepo-plugin#91]
Id like to request a feature that I had to workaround using extra variables under `env:`

Would be ideal if each `section` under `multirepo.repos` had the possibility to store (and render) additional information:

- `icon`: An icon to represent one of the sections
- `friendly_name`: A short text that describes the section
- `description`: A summary of the content on that section

Example:

```
plugins:
  - macros:
      verbose: true
  - search
  - multirepo:
      # (optional) tells multirepo to cleanup the temporary directory after site is built.
      cleanup: true
      # if set the docs directory will not be removed when importing docs. When using this with a nav section in an imported repo
      # you must keep the docs directory in the path (e.g., docs/path/to/file.md).
      keep_docs_dir: true
      repos:
        - section: 'User Guide'
          import_url: ''
          friendly_name: 'User Guide
          icon: 'res/userguide.svg'
          description: 'Entry level documentation'
        - section: 'adm-hw'
          import_url: ''
          friendly_name: 'Administration'
          icon: 'res/administrator.jpg'
          description: 'Topics related to infrastructure, monitoring, and cluster administration'
```

If that extra metadata were made available to be used with the macros plugin, then could be useful to also render home or landing pages with a little bit more customization, ie:

| [{icon}] \*\*{friendly_name}\*\*<br>[{description}]({section})<br> | [{icon}] \*\*{friendly_name}\*\*<br>[{description}]({section})<br> | [{icon}] \*\*{friendly_name}\*\*<br>[{description}]({section})<br> |
| ------------------------------------------------------------------ | ------------------------------------------------------------------ | ------------------------------------------------------------------ |
| [{icon}] \*\*{friendly_name}\*\*<br>[{description}]({section})<br> | [{icon}] \*\*{friendly_name}\*\*<br>[{description}]({section})<br> | [{icon}] \*\*{friendly_name}\*\*<br>[{description}]({section})<br> |

Even nicer would be if there was an option to render such table by enabling it in configuration or calling a macro directly on a markdown file, ie:

`[index.md]`

```
# Home

{{ multirepo_toc() }}
```

Or similar
