### ISSUE TITLE
Importing a repo not respecting nav structure from mkdocs.yml file

### ISSUE THREAD

**Issue by mlcooper** [jdoiro3/mkdocs-multirepo-plugin#98]
From the 'parent' mkdocs repo in my on-prem gitlab instance, I am importing another repo (from our gitlab on-prem instance) with this code:
```
INHERIT: mkdocs-inherit.yml

site_name: LightSpeed Documentation
site_url: http://cdte.pages.gitlab.redacted.com/docs/lightspeed/lightspeed
site_description: LightSpeed Platform Documentation
site_dir: public

plugins:
  - multirepo:
      cleanup: true
      keep_docs_dir: true
      repos:
        - section: Messaging
          import_url: git@gitlab.redacted.com:cdte/docs/lightspeed/lightspeed-docs-messaging.git?branch=main&edit_uri=/edit/main/docs/
```
In the repo which is being **imported**, I have this mkdocs.yml file:
```
---
site_name: LightSpeed Messaging
site_description: LightSpeed Messaging Documentation
site_url: https://cdte.pages.gitlab.redacted.com/docs/lightspeed/lightspeed/
repo_url: https://gitlab.redacted.com/cdte/docs/lightspeed/lightspeed-docs-messaging
edit_uri: ""
nav:
    - Architecture:
        - High Level Architecture: high_level_arch.md
        - Detailed Architecture: detailed_architecture.md
    - Onboarding:
        - How to Onboard: how_to_onboard.md
```  
The issue is that it appears the mkdocs-multirepo-plugin is not respecting the structure in the `nav:` block in the repo I am importing. As you can see here, there are no headings `Architecture` or `Onboarding`:
![Welcome](https://github.com/jdoiro3/mkdocs-multirepo-plugin/assets/9505606/8493ab41-f619-4f0c-85f3-ebacc88932b9)

I am using:
```
mkdocs --version
mkdocs, version 1.4.3 from /home/redacted/sourcecode/lightspeed/lightspeed-docs-parent/.venv/lib/python3.11/site-packages/mkdocs (Python 3.11)
mkdocs-multirepo-plugin v0.6.1
```
This feels just like https://github.com/jdoiro3/mkdocs-multirepo-plugin/issues/92 because my items are also rendering alphabetically and not following what my imported mkdocs.yml file has in its `nav` section. I've tried what this issue suggested, but I am not able to find a solution. This is the very last thing I'm working through, otherwise this plugin has been great. Thanks for assistance!
