### ISSUE TITLE
`section:` names do not preserve case

### ISSUE THREAD

**Issue by mlcooper** [jdoiro3/mkdocs-multirepo-plugin#99]
I am importing a few `section`'s like so:
```
plugins:
  - multirepo:
      cleanup: true
      keep_docs_dir: true
      repos:
        - section: Messaging
          import_url: git@gitlab.redacted.com:cdte/docs/lightspeed/lightspeed-docs-messaging.git?branch=main&edit_uri=/edit/main/docs/
        - section: Product APIs
          import_url: git@gitlab.redacted.com:cdte/docs/lightspeed/lightspeed-docs-api.git?branch=main&edit_uri=/edit/main/docs/
```
for `section: Product APIs`, I have also tried it `section: 'Product APIs'`, it is not preserving capitalization as shown here:
![Capital](https://github.com/jdoiro3/mkdocs-multirepo-plugin/assets/9505606/1ef09bef-532d-4085-b2c7-706818535e3e)

How can I have `section: Product APIs` show up as `Product APIs`, keeping capital/lower case letters as I have it in `mkdocs.yml`?

**Comment by Factorization** [comment]
I ran into this issue as well. Any updates?

It looks like it only affects the `section:`, but not the `section_path:`

**Comment by Factorization** [comment]
It looks like this is caused by this line: https://github.com/jdoiro3/mkdocs-multirepo-plugin/blob/main/mkdocs_multirepo_plugin/plugin.py#L215

If you don't `slugify` the `repo.section` it keeps the formatting. Do we need to slugify the section?

**Comment by cloudyparts** [comment]
Or add another field that when present overrides the slug?

```yaml
plugins:
  - multirepo:
      cleanup: true
      keep_docs_dir: true
      repos:
        - section: MSG
          label: "Messaging"
          import_url: git@gitlab.redacted.com:cdte/docs/lightspeed/lightspeed-docs-messaging.git?branch=main&edit_uri=/edit/main/docs/
        - section: API
          label: "Product APIs"
          import_url: git@gitlab.redacted.com:cdte/docs/lightspeed/lightspeed-docs-api.git?branch=main&edit_uri=/edit/main/docs/
```
